# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/containers/ocicrypt
%global goipath         github.com/containers/ocicrypt
Version:                1.2.0

%gometa -L

%global godevelheader   %{expand:
Requires: gnutls-utils}

%global common_description %{expand:
Encryption libraries for Encrypted OCI Container images.}

%global golicenses      LICENSE
%global godocs          docs ADOPTERS.md CODE-OF-CONDUCT.md README.md\\\
                        SECURITY.md

Name:           golang-github-containers-ocicrypt
Release:        %autorelease
Summary:        Encryption libraries for Encrypted OCI Container images

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
echo 'gnutls-utils'
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
