# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/gofri/go-github-ratelimit
%global goipath         github.com/gofri/go-github-ratelimit
Version:                1.1.0

%gometa -f

%global common_description %{expand:
A GoLang HTTP RoundTripper that handles GitHub API secondary rate limits.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A GoLang HTTP RoundTripper that handles GitHub API secondary rate limits

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
