# Generated by go2rpm 1.11.1
%bcond_without check
%global debug_package %{nil}

# https://github.com/thoas/go-funk
%global goipath         github.com/thoas/go-funk
Version:                0.9.3

%gometa -L

%global common_description %{expand:
A modern Go utility library which provides helpers (map, find, contains,
filter, ...).}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.rst

Name:           golang-github-thoas-funk
Release:        %autorelease
Summary:        Modern Go utility library which provides helpers

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
