# Generated by go2rpm 1.12.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/seccomp/libseccomp-golang
%global goipath         github.com/seccomp/libseccomp-golang
Version:                0.10.0

%gometa -L

%global common_description %{expand:
The libseccomp library provides an easy to use, platform independent, interface
to the Linux Kernel's syscall filtering mechanism.  The libseccomp API is
designed to abstract away the underlying BPF based syscall filter language and
present a more conventional function-call based filtering interface that should
be familiar to, and easily adopted by, application developers.

The libseccomp-golang library provides a Go based interface to the libseccomp
library.}

%global golicenses      LICENSE
%global godocs          CHANGELOG README

Name:           golang-github-seccomp-libseccomp
Release:        %autorelease
Summary:        Libseccomp Go bindings

License:        BSD-2-Clause
URL:            %{gourl}
Source:         %{gosource}

%if %{with check}
BuildRequires:  pkgconfig(libseccomp)
%endif

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%ifnarch i686 ppc64le s390x riscv64
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
