# Generated by go2rpm 1
# The test want to create a tun interface
%bcond_with check
%global debug_package %{nil}


# https://github.com/songgao/water
%global goipath         github.com/songgao/water
%global commit          2b4b6d7c09d80835e5f13f6b040d69f00a158b24

%gometa

%global common_description %{expand:
A simple TUN/TAP library written in native Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTORS README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        TUN/TAP library

# Automatically converted from old format: BSD - review is highly recommended.
License:        LicenseRef-Callaway-BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
