# Generated by go2rpm
# Tests need to be set up: https://github.com/jackc/pgx#testing
%bcond_with check
%global debug_package %{nil}


# https://github.com/jackc/pgx
%global goipath         github.com/jackc/pgx
Version:                4.10.1

%gometa

%global goaltipaths     github.com/jackc/pgx/v4

%global common_description %{expand:
Pgx is a pure Go driver and toolkit for PostgreSQL. pgx is different from other
drivers such as pq because, while it can operate as a database/sql compatible
driver, pgx is also usable directly. It offers a native interface similar to
database/sql that offers better performance and more features.}

%global golicenses      LICENSE
%global godocs          examples CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        PostgreSQL driver and toolkit for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/jackc/pgconn)
BuildRequires:  golang(github.com/jackc/pgconn/stmtcache)
BuildRequires:  golang(github.com/jackc/pgio)
BuildRequires:  golang(github.com/jackc/pgproto3/v2)
BuildRequires:  golang(github.com/jackc/pgtype)
BuildRequires:  golang(github.com/jackc/puddle)
BuildRequires:  golang(github.com/rs/zerolog)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(go.uber.org/zap)
BuildRequires:  golang(go.uber.org/zap/zapcore)
BuildRequires:  golang(golang.org/x/xerrors)
BuildRequires:  golang(gopkg.in/inconshreveable/log15.v2)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
