# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/schollz/progressbar
%global goipath         github.com/schollz/progressbar/v2
%global forgeurl        https://github.com/schollz/progressbar
Version:                2.15.0

%gometa

%global common_description %{expand:
A very simple thread-safe progress bar which should work on every OS without
problems. I needed a progressbar for croc and everything I tried had problems,
so I made another one.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Basic thread-safe progress bar for Golang applications

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/k0kubun/go-ansi)
BuildRequires:  golang(github.com/mitchellh/colorstring)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
# Needs network
%gocheck -d .
%endif

%gopkgfiles

%changelog
%autochangelog
