# Generated by go2rpm 1
%bcond_without check

%global debug_package %{nil}

# https://github.com/shurcooL/graphql
%global goipath         github.com/shurcooL/graphql
%global commit          18c5c3165e3af7c70ca625593f8066462ad684cc

%gometa

%global common_description %{expand:
Package graphql provides a GraphQL client implementation.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Package graphql provides a GraphQL client implementation

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/graph-gophers/graphql-go)
# Examples are not packaged
# BuildRequires:  golang(github.com/graph-gophers/graphql-go/example/starwars)
BuildRequires:  golang(github.com/graph-gophers/graphql-go/relay)
BuildRequires:  golang(golang.org/x/net/context/ctxhttp)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
