# Generated by go2rpm 1.12.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/prometheus/client_model
%global goipath         github.com/prometheus/client_model
Version:                0.6.1

%gometa -L

%global common_description %{expand:
Data model artifacts for Prometheus.}

%global golicenses      LICENSE NOTICE
%global godocs          CONTRIBUTING.md MAINTAINERS.md README.md

Name:           golang-github-prometheus-client-model
Release:        %autorelease
Summary:        Data model artifacts for Prometheus

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
