# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/unknwon/goconfig
%global goipath         github.com/unknwon/goconfig
%global commit          df7de6a44db81dd3ba39fa809f75e2063a6499d1

%gometa

%global goaltipaths     github.com/Unknwon/goconfig

%global common_description %{expand:
Package Goconfig is a fully functional and comments-support configuration file
(.ini) parser.}

%global golicenses      LICENSE
%global godocs          README.md README_ZH.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Fully functional and comments-support configuration file (.ini) parser

# Upstream license specification: Apache-2.0
# Automatically converted from old format: ASL 2.0 - review is highly recommended.
License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/smartystreets/goconvey/convey)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
