# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/alecthomas/colour
%global goipath         github.com/alecthomas/colour
Version:                0.1.0

%gometa

%global common_description %{expand:
Package Colour provides Quake-style colour formatting for Unix terminals.

The package level functions can be used to write to stdout (or strings or other
files). If stdout is not a terminal, colour formatting will be stripped.}

%global golicenses      COPYING
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Quake-style colour formatting for Unix terminals

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mattn/go-isatty)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
