# Generated by go2rpm 1.3
%bcond_without check

%global debug_package %{nil}

# https://github.com/mattbaird/jsonpatch
%global goipath         github.com/mattbaird/jsonpatch
%global commit          098863c1fc24cfea50cbe7e22422dde58707be02

%gometa

%global common_description %{expand:
JSON Patch allows you to generate JSON that describes changes you want to make
to a document, so you don't have to send the whole doc. JSON Patch format is
supported by HTTP PATCH method, allowing for standards based partial updates via
REST APIs.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        JSON Patch is specified in RFC 6902 from the IETF

# Upstream license specification: Apache-2.0
# Automatically converted from old format: ASL 2.0 - review is highly recommended.
License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/davecgh/go-spew/spew)
BuildRequires:  golang(github.com/evanphx/json-patch)
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
rm jsonpatch_array_at_root_test.go
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
