# Generated by go2rpm 1.8.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/dghubble/go-twitter
%global goipath         github.com/dghubble/go-twitter
%global commit          837915ec2f796f6b3784989489baf4751135bafa

%gometa

%global common_description %{expand:
Go Twitter REST and Streaming API v1.1.}

%global golicenses      LICENSE
%global godocs          examples CHANGES.md README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Go Twitter REST and Streaming API v1.1

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
