# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/mxk/go-flowrate
%global goipath         github.com/mxk/go-flowrate
%global commit          cca7078d478f8520f85629ad7c68962d31ed7682

%gometa

# Remove in F33
%global godevelheader %{expand:
Obsoletes:      golang-github-mxk-go-flowrate-devel < 0-0.13
}

%global common_description %{expand:
Go package for limiting and monitoring data flow rate.}

%global golicenses      LICENSE
%global godocs          README

%global gosupfiles      glide.lock glide.yaml

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Go package for limiting and monitoring data flow rate

# Upstream license specification: BSD-3-Clause
# Automatically converted from old format: BSD - review is highly recommended.
License:        LicenseRef-Callaway-BSD
URL:            %{gourl}
Source0:        %{gosource}
Source1:        glide.yaml
Source2:        glide.lock

%description
%{common_description}

%gopkg

%prep
%goprep
cp %{S:1} %{S:2} .

%install
%gopkginstall

# Remove in F33
# Remove erroneous glide.lock folder
%pretrans devel -p <lua>
path = "%{gopath}/src/%{goipath}/glide.lock"
st = posix.stat(path)
if st and st.type == "directory" then
  os.remove(path)
end

%if %{with check}
%check
%gocheck -d flowrate
%endif

%gopkgfiles

%changelog
%autochangelog
