# Generated by go2rpm 1.5.0
# Need zookeeper
%bcond_with check
%global debug_package %{nil}


# https://github.com/go-zookeeper/zk
%global goipath         github.com/go-zookeeper/zk
Version:                1.0.2

%gometa

%global common_description %{expand:
Native ZooKeeper client for Go.}

%global golicenses      LICENSE
%global godocs          _examples CONTRIBUTION.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Native ZooKeeper client for Go

# Upstream license specification: BSD-3-Clause
# Automatically converted from old format: BSD - review is highly recommended.
License:        LicenseRef-Callaway-BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Sep 02 2024 Miroslav Suchý <msuchy@redhat.com> - 1.0.2-1
- convert license to SPDX

* Mon Aug 09 2021 Robert-André Mauchin <zebob.m@gmail.com> 1.0.2-2
- Uncommitted changes

* Mon Aug 09 2021 Robert-André Mauchin <zebob.m@gmail.com> 1.0.2-1
- Initial release
