# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/jpillora/sizestr
%global goipath         github.com/jpillora/sizestr
Version:                1.0.0

%gometa

%global common_description %{expand:
Pretty print byte counts in Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Pretty print byte counts

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
