# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/jacobsa/oglematchers
%global goipath         github.com/jacobsa/oglematchers
%global commit          141901ea67cd4769c6800aa7bfdfc558fa22bda5

%gometa

%global common_description %{expand:
Oglematchers is a package for the Go programming language containing a set of
matchers, useful in a testing or mocking framework, inspired by and mostly
compatible with Google Test for C++ and Google JS Test. The package is used by
the ogletest testing framework and oglemock mocking framework, which may be more
directly useful to you, but can be generically used elsewhere as well.}

%global golicenses      LICENSE
%global godocs          README.md

%global gosupfiles      glide.lock glide.yaml

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Set of matchers for Go inspired by Google Test for C++ and Google JS Test

# Upstream license specification: Apache-2.0
# Automatically converted from old format: ASL 2.0 - review is highly recommended.
License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}
Source1:        glide.yaml
Source2:        glide.lock

%description
%{common_description}

%gopkg

%prep
%goprep
cp %{S:1} %{S:2} .

%install
%gopkginstall

# Remove in F33
# Remove erroneous glide.lock folder
%pretrans devel -p <lua>
path = "%{gopath}/src/%{goipath}/glide.lock"
st = posix.stat(path)
if st and st.type == "directory" then
  os.remove(path)
end

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
