# Generated by go2rpm 1
%bcond_without check

%global debug_package %{nil}

# https://github.com/jcmturner/rpc
%global goipath         gopkg.in/jcmturner/rpc.v0
%global forgeurl        https://github.com/jcmturner/rpc
Version:                0.0.2

%gometa

%global common_description %{expand:
Remote Procedure Call libraries
(https://pubs.opengroup.org/onlinepubs/9629399/).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Remote Procedure Call libraries

# Upstream license specification: Apache-2.0
License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
