# Generated by go2rpm
%bcond_without check
%global debug_package %{nil}

# https://github.com/alecthomas/kingpin
%global goipath         gopkg.in/alecthomas/kingpin.v2
%global forgeurl        https://github.com/alecthomas/kingpin
Version:                2.3.2

%gometa -f

%global common_description %{expand:
Kingpin is a fluent-style, type-safe command-line parser. It supports flags,
nested commands, and positional arguments.}

%global golicenses      COPYING
%global godocs          _examples README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go command line and flag parser

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}


%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
