# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate enumset_derive

Name:           rust-enumset_derive
Version:        0.10.0
Release:        %autorelease
Summary:        Internal helper crate for enumset

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/enumset_derive
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An internal helper crate for enumset. Not public API.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+proc-macro-crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+proc-macro-crate-devel %{_description}

This package contains library source intended for building other packages which
use the "proc-macro-crate" feature of the "%{crate}" crate.

%files       -n %{name}+proc-macro-crate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std_deprecation_warning-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std_deprecation_warning-devel %{_description}

This package contains library source intended for building other packages which
use the "std_deprecation_warning" feature of the "%{crate}" crate.

%files       -n %{name}+std_deprecation_warning-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
