# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate gethostname

Name:           rust-gethostname
Version:        0.4.3
Release:        %autorelease
Summary:        Gethostname for all platforms

License:        Apache-2.0
URL:            https://crates.io/crates/gethostname
Source:         %{crates_source}
# Automatically generated patch to strip foreign dependencies
Patch:          gethostname-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Gethostname for all platforms.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires
%if %{with check}
echo '/usr/bin/hostname'
%endif

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip a test that does not work in mock environments
%cargo_test -- -- --skip gethostname_matches_system_hostname
%endif

%changelog
%autochangelog
