# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate fiat-crypto

Name:           rust-fiat-crypto
Version:        0.2.8
Release:        %autorelease
Summary:        Correct-by-Construction Code for Cryptographic Primitives

License:        MIT OR Apache-2.0 OR BSD-1-Clause
URL:            https://crates.io/crates/fiat-crypto
Source:         %{crate}-%{version}-clean.crate
# script to create tarball with only permissible content:
# run "rust2rpm" and then "./gen_clean_tarball.sh" for new versions
Source:         gen_clean_tarball.sh
Source:         0001-remove-references-to-code-related-to-the-p434-curve.patch
# Manually created patch for downstream crate metadata changes
# * change crate description to something more meaningful
Patch:          fiat-crypto-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Correct-by-Construction Code for Cryptographic Primitives.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-BSD-1
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/AUTHORS
%doc %{crate_instdir}/CONTRIBUTORS
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
