# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate cmd_lib

Name:           rust-cmd_lib
Version:        1.9.4
Release:        %autorelease
Summary:        Common rust commandline macros and utils for shell script like tasks

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/cmd_lib
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
%if %{with check}
BuildRequires:  procps-ng
%endif

%global _description %{expand:
Common rust commandline macros and utils, to write shell script like
tasks easily.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
rm examples/tetris.{sh,rs}
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
