# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate bit_field

Name:           rust-bit_field
Version:        0.10.2
Release:        %autorelease
Summary:        Simple bit field trait providing get_bit, get_bits, set_bit, and set_bits methods for Rust's integral types

# Upstream license specification: Apache-2.0/MIT
License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/bit_field
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Simple bit field trait providing get_bit, get_bits, set_bit, and
set_bits methods for Rust's integral types.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/Changelog.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
