Name:		foremost
Version:	1.5.7
Release:	%autorelease
Summary:	Recover files by "carving" them from a raw disk
License:	LicenseRef-Fedora-Public-Domain
URL:		http://foremost.sf.net
Source0:	http://foremost.sourceforge.net/pkg/%{name}-%{version}.tar.gz
Patch0:		foremost-broken-jpeg.patch
Patch1:		foremost-fix-permission-timestamp.patch
Patch2:		foremost-1.5.7-format-security.patch
Patch3:		foremost-1.5.7-gcc10.patch
ExcludeArch:	%{ix86}
BuildRequires:	gcc
BuildRequires:	make

%description
Foremost recovers files files based on their headers, footers, and internal
data structures. This process is commonly referred to as data carving.
Foremost can work on a raw disk drive or image file generated by dd.  The
headers and footers can be specified by a configuration file or you can use
command line switches to specify built-in file types. These built-in types
look at the data structures of a given file format allowing for a more
reliable and faster recovery.

%prep
%autosetup

sed -i 's!/usr/local/etc/foremost.conf!%{_sysconfdir}/foremost.conf!' config.c
sed -i 's|^RAW_FLAGS =.*|RAW_FLAGS = %{optflags}|' Makefile

%build
make %{?_smp_mflags} CONF=%{_sysconfdir} V=1

%install
chmod 0644 *
mkdir -p $RPM_BUILD_ROOT%{_bindir}
mkdir -p $RPM_BUILD_ROOT%{_mandir}/man8
mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}
make install BIN=$RPM_BUILD_ROOT%{_bindir} MAN=$RPM_BUILD_ROOT%{_mandir}/man8 \
    CONF=$RPM_BUILD_ROOT%{_sysconfdir}

%files
%doc README CHANGES
%{_bindir}/*
%{_mandir}/man8/*
%config(noreplace) %{_sysconfdir}/foremost.conf

%changelog
%autochangelog
