# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/jedisct1/go-clocksmith
%global goipath         github.com/jedisct1/go-clocksmith
%global commit          da382b96386866f0af447149548e95bcbbd85395

%gometa

%global common_description %{expand:
A sleep-aware sleep() function, that doesn't pause (for too long) if the system
goes to hibernation.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Sleep-aware-sleep() function in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
