# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/bep/logg
%global goipath         github.com/bep/logg
Version:                0.4.0

%gometa -L -f

%global common_description %{expand:
A Fast and Structured logging package for Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-bep-logg
Release:        %autorelease
Summary:        A Fast and Structured logging package for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1
rm -rfv benchmarks/

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
