# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/NVIDIA/go-nvlib
%global goipath         github.com/NVIDIA/go-nvlib
Version:                0.7.0

%gometa -L -f

%global common_description %{expand:
A collection of useful Go libraries for use with NVIDIA GPU management tools.}

%global golicenses      LICENSE NOTICE
%global godocs          CONTRIBUTING.md README.md
%global gosupfiles      pkg/pciids/default_pci.ids

Name:           %{goname}
Release:        %autorelease
Summary:        A collection of useful Go libraries for use with NVIDIA GPU management tools

License:        Apache-2.0 AND (BSD-3-Clause OR GPL-2.0-or-later)
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
# The github.com/NVIDIA/go-nvlib/pkg/nvlib/device and
# github.com/NVIDIA/go-nvlib/pkg/nvlib/info and tests fail with:
# /tmp/go-build738952468/b001/device.test: symbol lookup error:
#   /tmp/go-build738952468/b001/device.test: undefined symbol:
#   nvmlGpuInstanceGetComputeInstanceProfileInfoV
#
# These were tried both with the proprietary NVIDIA driver version 565.77 and
# without.
%gocheck -d pkg/nvlib/device -d pkg/nvlib/info
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
