# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/jba/templatecheck
%global goipath         github.com/jba/templatecheck
Version:                0.7.1

%gometa -L -f

%global common_description %{expand:
Checking Go templates for validity.}

%global golicenses      LICENSE
%global godocs          README.md TODO.txt

Name:           golang-github-jba-templatecheck
Release:        %autorelease
Summary:        Checking Go templates for validity

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
