# Generated by go2rpm 1.9.0
%bcond_with check
%global debug_package %{nil}

# https://github.com/nats-io/stan.go
%global goipath         github.com/nats-io/stan.go
Version:                0.10.4

%gometa -f


%global common_description %{expand:
NATS Streaming is an extremely performant, lightweight reliable
streaming platform powered by NATS}

%global golicenses      LICENSE
%global godocs          examples CODE-OF-CONDUCT.md GOVERNANCE.md\\\
                        MAINTAINERS.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Performant, lightweight reliable streaming platform

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
