# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/bugsnag/bugsnag-go
%global goipath         github.com/bugsnag/bugsnag-go
Version:                2.2.0

%gometa -f


%global goaltipaths     github.com/bugsnag/bugsnag-go/v2

%global common_description %{expand:
Automatic panic monitoring for Go and Go web frameworks, like negroni, gin, and
revel.}

%global golicenses      LICENSE.txt
%global godocs          examples CHANGELOG.md CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Automatic panic monitoring for Go and Go web frameworks

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d . -d github.com/bugsnag/bugsnag-go/gin -d github.com/bugsnag/bugsnag-go/martini -d github.com/bugsnag/bugsnag-go/negroni
%endif


%gopkgfiles

%changelog
%autochangelog
