# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/mitchellh/go-homedir
%global goipath         github.com/mitchellh/go-homedir
Version:                1.1.0

%gometa

# Remove in F33:
%global godevelheader %{expand:
Obsoletes:      golang-github-mitchellh-go-homedir-devel < 1.1.0-3
}

%global common_description %{expand:
This is a Go library for detecting the user's home directory without the use of
cgo, so the library can be used in cross-compilation environments.

Usage is incredibly simple, just call homedir.Dir() to get the home directory
for a user, and homedir.Expand() to expand the ~ in a path to the home
directory.}

%global golicenses      LICENSE
%global godocs          README.md

%global gosupfiles glide.lock glide.yaml

Name:           %{goname}
Release:        %autorelease
Summary:        Go library for detecting and expanding the user's home directory without cgo

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
Source1:        glide.yaml
Source2:        glide.lock

%description
%{common_description}

%gopkg

%prep
%goprep
cp %{S:1} %{S:2} .

%install
%gopkginstall

# Remove in F33
# Remove erroneous glide.lock folder
%pretrans devel -p <lua>
path = "%{gopath}/src/%{goipath}/glide.lock"
st = posix.stat(path)
if st and st.type == "directory" then
  os.remove(path)
end

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
