# Generated by go2rpm 1
%bcond_without check

%global debug_package %{nil}

# https://github.com/go-chi/cors
%global goipath         github.com/go-chi/cors
Version:                1.2.0

%gometa

%global common_description %{expand:
go-chi/cors is a fork of github.com/rs/cors that 
provides a net/http compatible middleware for 
performing pref-light CORS checks on the server 
side. These headers are required for using the 
browser native Fetch API.

This middleware is designed to be used as a 
top-level middleware on the chi router. 
Applying with within a r.Group() or using With() 
will not work without routes matching OPTIONS added.}

%global golicenses      LICENSE
%global godocs          _example README.md

Name:           %{goname}
Release:        %autorelease
Summary:        CORS net/http middleware for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
