# Generated by go2rpm
# tests are broken except when run in very specific ways
%bcond_with check
%global debug_package %{nil}


# https://github.com/mgutz/logxi
%global goipath         github.com/mgutz/logxi
Version:                1

%gometa

%global common_description %{expand:
Log XI is a structured 12-factor app logger built for speed and happy
development.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        12-factor app logger built for performance and happy development

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mattn/go-colorable)
BuildRequires:  golang(github.com/mattn/go-isatty)
BuildRequires:  golang(github.com/mgutz/ansi)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf Gododir

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
