# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/gophercloud/gophercloud
%global goipath         github.com/gophercloud/gophercloud/v2
Version:                2.4.0

%gometa -L -f

%global common_description %{expand:
Gophercloud: an OpenStack SDK for Go.}

%global golicenses      LICENSE
%global godocs          docs CHANGELOG.md README.md RELEASE.md

Name:           golang-github-gophercloud2
Release:        %autorelease
Summary:        An OpenStack SDK for Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
