# Generated by go2rpm 1
%bcond_without check

%global debug_package %{nil}

# https://github.com/creack/goselect
%global goipath         github.com/creack/goselect
Version:                0.1.2

%gometa

%global common_description %{expand:
Select(2) implementation in Go.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Select(2) implementation in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
Patch0001:      https://github.com/creack/goselect/pull/18.patch

%description
%{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
