# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/digitalocean/godo
%global goipath         github.com/digitalocean/godo
Version:                1.111.0

%gometa -L -f


%global common_description %{expand:
DigitalOcean Go API client.}

%global golicenses      LICENSE.txt
%global godocs          CHANGELOG.md CONTRIBUTING.md README.md

Name:           golang-github-digitalocean-godo
Release:        %autorelease
Summary:        DigitalOcean Go API client

License:        BSD-3-Clause and MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
