# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/lithammer/fuzzysearch
%global goipath         github.com/lithammer/fuzzysearch
Version:                1.1.8

%gometa

%global common_description %{expand:
Inspired by bevacqua/fuzzysearch, a fuzzy matching library written in
JavaScript. But contains some extras like ranking using Levenshtein distance
(see RankMatch()) and finding matches in a list of words (see Find()).

Fuzzy searching allows for flexibly matching a string with partial input,
useful for filtering data very quickly based on lightweight user input.

The current implementation uses the algorithm suggested by Mr. Aleph, a russian
compiler engineer working at V8.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Tiny and fast fuzzy search in Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
