# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/c2h5oh/datasize
%global goipath         github.com/c2h5oh/datasize
%global commit          859f65c6625b78dfa569149781d2e753c40a1db5

%gometa -f

%global common_description %{expand:
Golang helpers for data sizes (kilobytes, petabytes), human readable sizes,
parsing.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Golang helpers for data sizes, human readable sizes, parsing

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
