# Generated by go2rpm 1.8.0
%bcond_without check
%global debug_package %{nil}

# We just want httputil
# The rest will be deprecated soon because Golang is moving to pkg.go.dev
# https://github.com/golang/gddo
%global goipath         github.com/golang/gddo
%global commit          20d68f94ee1f7547de2b1c68627253df20c8d45e

%gometa

%global goname golang-github-gddo
%global godevelname golang-github-gddo-httputil-devel

%global common_description %{expand:
The code in this project is designed to be used by godoc.org.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.markdown

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Go Doc Dot Org

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
find . -mindepth 1 -maxdepth 1 -type d -not -name "httputil" -and -not -name "_build" -exec rm -rf "{}" \;

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
