# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/rootless-containers/rootlesskit
%global goipath         github.com/rootless-containers/rootlesskit
Version:                1.0.1

%gometa -f

%global common_description %{expand:
Linux-native "fake root" for implementing rootless containers.}

%global golicenses      LICENSE
%global godocs          docs README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Linux-native "fake root" for implementing rootless containers

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}
Patch0:         Disable-vpnkit.patch

%description %{common_description}

%gopkg

%prep
%goprep
# vpnkit not packageable right now due to K8S incompatibility
%patch -P0 -p1
rm -rfv pkg/network/vpnkit

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck -d pkg/port/builtin
%endif

%files
%license LICENSE
%doc docs README.md
%{_bindir}/rootlessctl
%{_bindir}/rootlesskit-docker-proxy
%{_bindir}/rootlesskit

%gopkgfiles

%changelog
%autochangelog
