# Generated by go2rpm
%bcond_without check

%global debug_package %{nil}

# https://github.com/hashicorp/go-cleanhttp
%global goipath         github.com/hashicorp/go-cleanhttp
Version:                0.5.1

%gometa

# Remove in F33:
%global godevelheader %{expand:
Obsoletes:      golang-github-hashicorp-go-cleanhttp-devel < 0.5.1-2
}

%global common_description %{expand:
Convenience utilities for acquiring "clean" http.Transport and http.Client
structs}

%global golicenses      LICENSE
%global godocs          README.md

%global gosupfiles glide.lock glide.yaml

Name:           %{goname}
Release:        %autorelease
Summary:        Convenience utilities for "clean" http.Transport and http.Client structs

# Upstream license specification: MPL-2.0
License:        MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
Source1:        glide.yaml
Source2:        glide.lock
# https://github.com/hashicorp/go-cleanhttp/issues/14
Patch0:         https://github.com/hashicorp/go-cleanhttp/commit/d3fcbee8e1810ecee4bdbf415f42f84cfd0e3361.patch#/0001-Fix-tests-against-newer-Go.patch

%description
%{common_description}

%gopkg

%prep
%goprep
%patch -P0 -p1
cp %{S:1} %{S:2} .

%install
%gopkginstall

# Remove in F33
# Remove erroneous glide.lock folder
%pretrans devel -p <lua>
path = "%{gopath}/src/%{goipath}/glide.lock"
st = posix.stat(path)
if st and st.type == "directory" then
  os.remove(path)
end

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
