# Generated by go2rpm 1.8.1
# Needs network
%bcond_with check
%global debug_package %{nil}

# https://github.com/ishidawataru/sctp
%global goipath         github.com/ishidawataru/sctp
%global commit          9a39160e9062ad0b3e6522f838a116918e58a811

%gometa

%global common_description %{expand:
Stream Control Transmission Protocol library for the Go programming language.}

%global golicenses      LICENSE NOTICE
%global godocs          example README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        SCTP library for the Go programming language

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
