# Generated by go2rpm 1
%bcond_without check

%global debug_package %{nil}

# https://github.com/golang-sql/civil
%global goipath         github.com/golang-sql/civil
%global commit          cb61b32ac6fe84d34b81730175f91965e43d0f90

%gometa

%global common_description %{expand:
Civil Date and Time package for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Civil Date and Time package for Go

# Upstream license specification: Apache-2.0
# Automatically converted from old format: ASL 2.0 - review is highly recommended.
License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
