# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/jfrog/jfrog-cli
%global goipath         github.com/jfrog/jfrog-cli
Version:                2.87.0

%gometa -L -f


Name:           jfrog-cli
Release:        %autorelease
Summary:        CLI to automate access to JFrog products

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND LicenseRef-Fedora-Public-Domain AND MIT AND MPL-2.0 AND Unlicense
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
JFrog CLI is a client that provides a simple interface that automates access to
the JFrog products.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1
# these tests require access to Artifactory instance
rm -v \
  access_test.go \
  artifactorybulkrepository_test.go \
  artifactory_test.go \
  buildinfo_test.go \
  distribution_test.go \
  docker_test.go \
  evidence_test.go \
  go_test.go \
  gradle_test.go \
  helm_test.go \
  ide_test.go \
  lifecycle_test.go \
  main_test.go \
  maven_test.go \
  npm_test.go \
  nuget_test.go \
  pipenv_test.go \
  pip_test.go \
  plugins_test.go \
  poetry_test.go \
  transfer_test.go \

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/jf %{goipath}
%{gobuilddir}/bin/jf completion bash > jf.bash
%{gobuilddir}/bin/jf completion fish > jf.fish
%{gobuilddir}/bin/jf completion zsh  > jf.zsh

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -Dpm 0644 jf.bash %{buildroot}%{bash_completions_dir}/jf
install -Dpm 0644 jf.fish %{buildroot}%{fish_completions_dir}/jf.fish
install -Dpm 0644 jf.zsh  %{buildroot}%{zsh_completions_dir}/_jf

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs CONTRIBUTING.md README.md RELEASE.md
%doc documentation/CLI-for-JFrog-Cloud-Transfer.md
%doc documentation/CLI-for-JFrog-Curation.md
%doc documentation/CLI-for-JFrog-Distribution.md
%doc documentation/CLI-for-JFrog-Lifecycle.md
%doc documentation/CLI-for-JFrog-Mission-Control.md
%doc documentation/CLI-for-JFrog-Pipelines.md
%doc documentation/CLI-for-JFrog-Xray.md documentation/JFrog-CLI.md
%doc guides/getting-started-with-jfrog-using-the-cli.md
%doc guides/jfrog-cli-plugins-developer-guide.md
%{_bindir}/jf
%{bash_completions_dir}/jf
%{fish_completions_dir}/jf.fish
%{zsh_completions_dir}/_jf

%changelog
%autochangelog
