#global commit db518f882c19b04c72d1be26f6a43bd0e611ee18
%global shortcommit %(c=%{commit}; echo ${c:0:7})

Name:           Mayavi
Version:        4.8.2
Release:        %autorelease
Summary:        Scientific data 3-dimensional visualizer
# Automatically converted from old format: BSD and EPL and LGPLv2+ and LGPLv2 and LGPLv3 - review is highly recommended.
License:        LicenseRef-Callaway-BSD AND LicenseRef-Callaway-EPL AND LicenseRef-Callaway-LGPLv2+ AND LicenseRef-Callaway-LGPLv2 AND LGPL-3.0-only
URL:            http://code.enthought.com/projects/mayavi/
Source0:        https://github.com/enthought/mayavi/archive/%{version}/mayavi-%{version}.tar.gz
Source1:        mayavi2.desktop
# NumPy 2.x patch
# https://github.com/enthought/mayavi/pull/1315
Patch:          https://github.com/enthought/mayavi/pull/1315.patch
BuildRequires:  gcc
BuildRequires:  make
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-Cython
BuildRequires:  python%{python3_pkgversion}-setuptools
# For tests
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  python%{python3_pkgversion}-pytest-xvfb
BuildRequires:  python%{python3_pkgversion}-apptools
BuildRequires:  python%{python3_pkgversion}-qt5
BuildRequires:  python%{python3_pkgversion}-traits
BuildRequires:  python%{python3_pkgversion}-traitsui
BuildRequires:  python%{python3_pkgversion}-numpy
BuildRequires:  python%{python3_pkgversion}-vtk
# For HTML docs
BuildRequires:  /usr/bin/sphinx-build-3
Requires:       python%{python3_pkgversion}-mayavi
BuildRequires:  desktop-file-utils 
BuildRequires:  xwayland-run
ExcludeArch:    %{ix86}

%description
The Mayavi project includes two related packages for 3-dimensional 
visualization:

 * Mayavi2: A tool for easy and interactive visualization of data.
 * TVTK: A Traits-based wrapper for the Visualization Toolkit, a
   popular open-source visualization library.

These operate at different levels of abstraction. TVTK manipulates
visualization objects, while Mayavi2 lets you operate on your data,
and then see the results. Most users either use the Mayavi user
interface or program to its scripting interface; you probably don't
need to interact with TVTK unless you want to create a new Mayavi
module.


%package -n python%{python3_pkgversion}-mayavi
Summary:        Python 3 mayavi module
Requires:       python%{python3_pkgversion}-vtk
Requires:       python%{python3_pkgversion}-apptools
Requires:       python%{python3_pkgversion}-traitsui
Requires:       python%{python3_pkgversion}-envisage
Requires:       python%{python3_pkgversion}-pyface-qt
%{?python_provide:%python_provide python%{python3_pkgversion}-mayavi}

%description -n python%{python3_pkgversion}-mayavi
Python 3 mayavi module


%package doc
Summary:        Documentation for %{name}

%description doc
Documentation for %{name}.


%prep
%autosetup -p1 -n mayavi-%{version}

# vtk not discoverable by pkg_resources
sed -i -e "/^ *'vtk'/d" mayavi/__init__.py

# Remove pregenerated C sources
grep -lr '/\* Generated by Cython' | xargs rm -v

# fix wrong-file-end-of-line-encoding
for file in *.txt examples/mayavi/data/room_vis.wrl examples/tvtk/dscene.py \
 examples/mayavi/interactive/wx_mayavi_embed*.py ; do
 sed "s|\r||g" $file > $file.new && \
 touch -r $file $file.new && \
 mv $file.new $file
done

# file-not-utf8
for file in *.txt docs/*.txt; do
 iconv -f ISO-8859-1 -t UTF-8 -o $file.new $file && \
 touch -r $file $file.new && \
 mv $file.new $file
done

# remove shebang
for file in mayavi/scripts/*.py; do
 sed '/^#!\//, 1d' $file > $file.new && \
 touch -r $file $file.new && \
 mv $file.new $file
done

# fix shebang
%py3_shebang_fix mayavi/scripts/mayavi2 mayavi/tests/{csv_files/csv_2_py,runtests.py}

# remove exec permission
find examples -type f -exec chmod 0644 {} ";"
chmod 0644 mayavi/tests/data/cellsnd.ascii.inp

%build
# Recythonize the sources
find -name '*.pyx' -exec cython --verbose {} \;

%py3_build
# Need xwfb-run for html doc building
SPHINXBUILD=/usr/bin/sphinx-build-3 xwfb-run -- %{__python3} setup.py build_docs

%install
%py3_install

# fix wrong-file-end-of-line-encoding
for file in docs/build/mayavi/html/_downloads/wx_mayavi*.py; do
 sed "s|\r||g" $file > $file.new && \
 touch -r $file $file.new && \
 mv $file.new $file
done

mkdir -p $RPM_BUILD_ROOT%{_mandir}/man1/
cp -p docs/mayavi2.man $RPM_BUILD_ROOT/%{_mandir}/man1/mayavi2.1

desktop-file-install --dir=${RPM_BUILD_ROOT}%{_datadir}/applications %{SOURCE1}
mkdir -p $RPM_BUILD_ROOT%{_datadir}/icons/hicolor/48x48/apps/
install -p -m 644 ./docs/source/mayavi/images/mayavi2-48x48.png \
 $RPM_BUILD_ROOT%{_datadir}/icons/hicolor/48x48/apps/mayavi2.png

%check
%pytest -v mayavi

%files
%license *LICENSE*
%doc README-tvtk.txt docs/*.txt
%{_bindir}/mayavi2
%{_bindir}/tvtk_doc
%{_mandir}/man1/mayavi2.1.*
%{_datadir}/applications/mayavi2.desktop
%{_datadir}/icons/hicolor/48x48/apps/mayavi2.png

%files -n python%{python3_pkgversion}-mayavi
%license *LICENSE*
%doc docs/*.txt README-tvtk.txt
%dir %{python3_sitearch}/mayavi
%{python3_sitearch}/mayavi/[_a-gi-z]*
%{python3_sitearch}/mayavi*.egg-info
%{python3_sitearch}/tvtk/

%files doc
%license *LICENSE*
%doc README-tvtk.txt docs/*.txt docs/build/mayavi docs/build/tvtk examples/


%changelog
%autochangelog
