Name:           perl-Log-Report-Template
Version:        1.04
Release:        1%{?dist}
Summary:        Template Toolkit with translations
License:        GPL-1.0-or-later OR Artistic-1.0-Perl
URL:            https://metacpan.org/dist/Log-Report-Template
Source0:        https://cpan.metacpan.org/authors/id/M/MA/MARKOV/Log-Report-Template-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  coreutils
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(:VERSION) >= 5.16
BuildRequires:  perl(Config)
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
# Run-time:
BuildRequires:  perl(base)
BuildRequires:  perl(File::Find)
BuildRequires:  perl(Log::Report) >= 1.42
BuildRequires:  perl(Log::Report::Domain)
# Log::Report::Extract version from Log::Report::Lexicon in META.json
BuildRequires:  perl(Log::Report::Extract)
BuildRequires:  perl(Log::Report::Message)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(String::Print) >= 0.91
BuildRequires:  perl(Template) >= 2.26
BuildRequires:  perl(Template::Filters)
# Tests
BuildRequires:  perl(constant)
BuildRequires:  perl(File::Basename)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(lib)
BuildRequires:  perl(Log::Report::Lexicon::POT)
BuildRequires:  perl(Test::More) >= 1
Requires:       perl(Log::Report) >= 1.42
Requires:       perl(String::Print) >= 0.91
Requires:       perl(Template) >= 2.26

# Remove under-specified dependencies
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^perl\\((Log::Report|String::Print|Template|Test::More)\\)$

%description
This module extends Template, which is the core of Template Toolkit. The main
addition is support for translations via the translation framework offered by
Log::Report.

%package tests
Summary:        Tests for %{name}
Requires:       %{name} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires:       coreutils
Requires:       perl-Test-Harness
Requires:       perl(Log::Report) >= 1.42
Requires:       perl(Test::More) >= 1

%description tests
Tests from %{name}. Execute them
with "%{_libexecdir}/%{name}/test".

%prep
%setup -q -n Log-Report-Template-%{version}
# Correct shebangs
for F in t/*.t; do
    perl -i -MConfig -ple 'print $Config{startperl} if $. == 1 && !s{\A#!\s*perl}{$Config{startperl}}' "$F"
    chmod +x "$F"
done

%build
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%install
%{make_install}
%{_fixperms} %{buildroot}/*
# Install tests
mkdir -p %{buildroot}%{_libexecdir}/%{name}
cp -a t %{buildroot}%{_libexecdir}/%{name}
cat > %{buildroot}%{_libexecdir}/%{name}/test << 'EOF'
#!/bin/bash
set -e
# t/41double.t reads and writes into t/lexicons/first.utf-8.po
DIR=$(mktemp -d)
cp -a %{_libexecdir}/%{name}/* "$DIR"
pushd "$DIR"
prove -I . -j "$(getconf _NPROCESSORS_ONLN)"
popd
rm -r "$DIR"
EOF
chmod +x %{buildroot}%{_libexecdir}/%{name}/test

%check
export HARNESS_OPTIONS=j$(perl -e 'if ($ARGV[0] =~ /.*-j([0-9][0-9]*).*/) {print $1} else {print 1}' -- '%{?_smp_mflags}')
make test

%files
%doc ChangeLog README.md
%dir %{perl_vendorlib}/Log
%dir %{perl_vendorlib}/Log/Report
%{perl_vendorlib}/Log/Report/Template
%{perl_vendorlib}/Log/Report/Template.pm
%{perl_vendorlib}/Log/Report/Template.pod
%{_mandir}/man3/Log::Report::Template.*
%{_mandir}/man3/Log::Report::Template::*

%files tests
%{_libexecdir}/%{name}

%changelog
* Wed Nov 05 2025 Petr Pisar <ppisar@redhat.com> 1.04-1
- Specfile autogenerated by cpanspec 1.78.
