%global srcname     astroid

Version:        3.3.5

Name:           python-astroid
# Note: please check that this doesn't break pylint before committing and building! -GC
Release:        %autorelease
Summary:        Common base representation of python source code for pylint and other projects
License:        LGPL-2.1-or-later
URL:            https://pypi.org/project/astroid/
Source0:        https://github.com/pylint-dev/%{srcname}/archive/v%{version}/%{srcname}-%{version}.tar.gz
BuildArch:      noarch

BuildRequires:  python3-devel
BuildRequires:  python3-pytest
BuildRequires:  python3-setuptools

%global _description %{expand:
The aim of this module is to provide a common base representation of python
source code for projects such as pychecker, pyreverse, pylint...
It provides a compatible representation which comes from the _ast module. It
rebuilds the tree generated by the builtin _ast module by recursively walking
down the AST and building an extended ast. The new node classes have additional
methods and attributes for different usages. They include some support for
static inference and local name scopes. Furthermore, astroid builds partial
trees by inspecting living objects.}

%description %_description

%package -n python3-%{srcname}
Summary:        %{summary}
%{?python_provide:%python_provide python3-%{srcname}}

%description -n python3-%{srcname} %_description

%prep
%autosetup -n %{srcname}-%{version} -p1

%generate_buildrequires
%pyproject_buildrequires

%build
%pyproject_wheel

%install
%pyproject_install
# https://github.com/pylint-dev/astroid/pull/2156#issuecomment-1612640531
rm -rf %{buildroot}%{python3_sitelib}/tests


%check
# deselected tests fail with Python 3.13
# https://github.com/pylint-dev/astroid/issues/2349
%{python3} -m pytest -v \
  --deselect "tests/test_inference.py::InferenceTest::test_getitem_of_class_raised_type_error"  \
  --deselect "tests/test_inference.py::test_dataclasses_subscript_inference_recursion_error_39" \
  --deselect "tests/brain/test_brain.py::TypingBrain::test_typing_annotated_subscriptable" \
  --deselect "tests/brain/test_pathlib.py::test_inference_parents" \
  --deselect "tests/brain/test_pathlib.py::test_inference_parents_subscript_index"


%files -n python3-%{srcname}
%license LICENSE
%{python3_sitelib}/astroid
%{python3_sitelib}/astroid*.dist-info/

%changelog
%autochangelog
