%global commit 2402f9b7fb7c15d01398cdd5f58f124a920517b2

Name:           python-ruamel-yaml-clib
Version:        0.2.12
Release:        %autorelease
Summary:        C version of reader, parser and emitter for ruamel.yaml derived from libyaml

# SPDX
License:        MIT
URL:            https://sourceforge.net/projects/ruamel-yaml-clib
Source0:        https://sourceforge.net/code-snapshots/hg/r/ru/ruamel-yaml-clib/code/ruamel-yaml-clib-code-%{commit}.zip

Patch:          unbundle-libyaml.patch

# Adjust setup.py for the removal of deprecated ast classes
# Fixes build with Python 3.14
# https://sourceforge.net/p/ruamel-yaml/code/merge-requests/9/
Patch:          9.patch

BuildRequires:  gcc

%global _description %{expand:
It is the C based reader/scanner and emitter for ruamel.yaml.}

%description %{_description}

%package -n     python3-ruamel-yaml-clib
Summary:        %{summary}

BuildRequires:  python3-devel
BuildRequires:  %{py3_dist Cython}
BuildRequires:  libyaml-devel

# Unfortunately, the circular dependency is intentional; the clib extension
# packaged here imports from ruamel.yaml, which in turn uses the extension for
# performance.
BuildRequires:  python3-ruamel-yaml
Requires:       python3-ruamel-yaml

%py_provides python3-ruamel.yaml.clib

%description -n python3-ruamel-yaml-clib %{_description}

%prep
%autosetup -p1 -n ruamel-yaml-clib-code-%{commit}

# Fix wrong return type for strlen()
sed -i 's/int strlen/size_t strlen/' _ruamel_yaml.pxd

# Remove bundled libyaml source files
rm -v api.c dumper.c emitter.c loader.c parser.c reader.c scanner.c writer.c config.h yaml_private.h yaml.h

# Force regenerating C files from Cython sources
rm -v $(grep -rl '/\* Generated by Cython')

%generate_buildrequires
# Upstream has a tox.ini, but it is for a build-and-install check, not a test
# suite, so we do not use it to generate dependencies (-t).
%pyproject_buildrequires

%build
# cython refuses to cythonize a file in a directory that cannot be a Python
# module ¯\_(ツ)_/¯
#
# Top-level structure seems to be incompatible with Cython 0.29.34
# ('ruamel-yaml-clib-code._ruamel_yaml' is not a valid module name)
# https://sourceforge.net/p/ruamel-yaml-clib/tickets/14/
mkdir ruamel.yaml.clib
mv *.pyx ruamel.yaml.clib
cythonize -j${RPM_BUILD_NCPUS} -3 ruamel.yaml.clib/*.pyx
mv ruamel.yaml.clib/* .
rmdir ruamel.yaml.clib

%pyproject_wheel

%install
%pyproject_install
%pyproject_save_files -l _ruamel_yaml

%check
%py3_check_import _ruamel_yaml

%files -n python3-ruamel-yaml-clib -f %{pyproject_files}
%doc README.md

%changelog
%autochangelog
