%global	gem_name	graphene1

%global	gem_ver	4.3.6
%global	gem_ver_escaped %(v=%{gem_ver}; echo ${v} | sed -e 's|\\.|\\\\.|g')

Name:		rubygem-%{gem_name}
Version:	%{gem_ver}
Release:	1%{?dist}

Summary:	Ruby/Graphene1 is a Ruby binding of Graphene
License:	LGPL-2.1-or-later
URL:		https://ruby-gnome.github.io/
Source0:	https://rubygems.org/gems/%{gem_name}-%{version}.gem
Source1:	%{gem_name}-%{version}-test-missing-files.tar.gz
# Source1 is generated by the $ bash %%SOURCE2 %%version
Source2:	%{gem_name}-create-missing-test-files.sh

BuildRequires:	ruby(release)
BuildRequires:	rubygems-devel
BuildRequires:	ruby
#%%check
BuildRequires:	rubygem(test-unit)
BuildRequires:	rubygem-glib2-devel
BuildRequires:	rubygem(gobject-introspection)
BuildRequires:	graphene
Requires:		graphene

BuildArch:		noarch

%description
Ruby/Graphene1 is a Ruby binding of Graphene.

%package	doc
Summary:	Documentation for %{name}
Requires:	%{name} = %{version}-%{release}
BuildArch:	noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n %{gem_name}-%{version} -a 1
# Allow higher version of other ruby-gnome suite pkgs
sed -i ../%{gem_name}-%{version}.gemspec \
	-e 's|= %{gem_ver_escaped}|>= %{gem_ver}|' 

%build
gem build ../%{gem_name}-%{version}.gemspec
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
	%{buildroot}%{gem_dir}/

rm -f %{buildroot}%{gem_cache}
pushd %{buildroot}%{gem_instdir}
rm -f \
	Rakefile \
	%{gem_name}.gemspec \
	%{nil}
popd

%check
cp -a %{gem_name}/test .%{gem_instdir}
pushd .%{gem_instdir}

export RUBYLIB=%{buildroot}%{gem_libdir}:$(pwd)/test
sed -i test/run.rb \
	-e '\@run-test@s|require_relative "../../|require "|'
ruby ./test/run.rb

popd

%files
%dir	%{gem_instdir}
%license	%{gem_instdir}/COPYING.LIB
%doc	%{gem_instdir}/README.md
%{gem_libdir}
%{gem_spec}

%files doc
%doc	%{gem_docdir}

%changelog
* Thu Apr 30 2026 Mamoru TASAKA <mtasaka@fedoraproject.org> - 4.3.6-1
- Initial package
