# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate gstreamer-utils

Name:           rust-gstreamer-utils
Version:        0.24.0
Release:        %autorelease
Summary:        GStreamer Rust APIs for linking producers and consumers

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/gstreamer-utils
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Exposes an object to build several Gst pipeline with one producer and
several consumer.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_22-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_22-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_22" feature of the "%{crate}" crate.

%files       -n %{name}+v1_22-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_24-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_24-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_24" feature of the "%{crate}" crate.

%files       -n %{name}+v1_24-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_26-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_26-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_26" feature of the "%{crate}" crate.

%files       -n %{name}+v1_26-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
