# Generated by rust2rpm 24
%bcond_without check

%global crate elfcat

Name:           rust-elfcat
Version:        0.1.8
Release:        %autorelease
Summary:        ELF visualizer. Generates HTML files from ELF binaries

License:        Zlib
URL:            https://crates.io/crates/elfcat
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
ELF visualizer. Generates HTML files from ELF binaries.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license license
%doc changelog.md
%doc readme.md
%{_bindir}/elfcat

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
