# Generated by rust2rpm 27
# * test fixtures are not included in published crates
%bcond check 0
%global debug_package %{nil}

%global crate jpegxl-sys
%global crate_version 0.11.2+libjxl-0.11.1

Name:           rust-jpegxl-sys
Version:        0.11.2
Release:        %autorelease
Summary:        Rust wrapper for JPEG XL reference implementation

License:        GPL-3.0-or-later
URL:            https://crates.io/crates/jpegxl-sys
Source:         %{crates_source %{crate} %{crate_version}}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          jpegxl-sys-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
# * drop feature for statically linking libjxl
Patch:          jpegxl-sys-fix-metadata.diff
Patch:          0001-unconditionally-use-pkg-config-to-find-libjxl.patch

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(libjxl) >= 0.8.2

%global _description %{expand:
Rust wrapper for JPEG XL reference implementation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libjxl) >= 0.8.2

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+docs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+docs-devel %{_description}

This package contains library source intended for building other packages which
use the "docs" feature of the "%{crate}" crate.

%files       -n %{name}+docs-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{crate_version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
