# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate difference

Name:           rust-difference
Version:        2.0.0
Release:        %autorelease
Summary:        Rust text diffing and assertion library

License:        MIT
URL:            https://crates.io/crates/difference
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * bump quickcheck dev-dependency from 0.4 to 1.0:
#   https://github.com/johannhof/difference.rs/pull/38
# * bump term dev-dependency from 0.2 to 0.7:
#   https://github.com/johannhof/difference.rs/pull/42
# * remove useless executable and related dependencies and features
Patch:          difference-fix-metadata.diff
# * fix deprecated syntax for inclusive range:
#   https://github.com/johannhof/difference.rs/pull/41
Patch:          0001-Fix-inclusive-range.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A Rust text diffing and assertion library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/Examples.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
