# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate wax

Name:           rust-wax
Version:        0.6.0
Release:        %autorelease
Summary:        Opinionated and portable globs that can be matched against paths and directory trees

License:        MIT
URL:            https://crates.io/crates/wax
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Opinionated and portable globs that can be matched against paths and
directory trees.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+walk-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+walk-devel %{_description}

This package contains library source intended for building other packages which
use the "walk" feature of the "%{crate}" crate.

%files       -n %{name}+walk-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
