# Generated by rust2rpm 28
# * no tests are shipped with the published crates
# * example code adds an unnecessary dependency on libc-print (not packaged)
%bcond check 0
%global debug_package %{nil}

%global crate ctor

Name:           rust-ctor
Version:        1.0.13
Release:        %autorelease
Summary:        Global, no_std-compatible constructors for all platforms that run before main

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/ctor
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Global, no_std-compatible constructors for all platforms that run before
main (like C/C++ __attribute__((constructor))).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+priority-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+priority-devel %{_description}

This package contains library source intended for building other packages which
use the "priority" feature of the "%{crate}" crate.

%files       -n %{name}+priority-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+proc_macro-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+proc_macro-devel %{_description}

This package contains library source intended for building other packages which
use the "proc_macro" feature of the "%{crate}" crate.

%files       -n %{name}+proc_macro-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
