# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate rancor

Name:           rust-rancor
Version:        0.1.0
Release:        %autorelease
Summary:        Scalable and efficient error handling without type composition

License:        MIT
URL:            https://crates.io/crates/rancor
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  dos2unix

%global _description %{expand:
Scalable and efficient error handling without type composition.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
# The crate has a mixture of newline styles.
# https://github.com/rkyv/rancor/commit/b65012a3848487155c072682b151f50599404bae
find . -type f | xargs -r -t dos2unix --keepdate
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
