# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate gix-tempfile

Name:           rust-gix-tempfile
Version:        14.0.2
Release:        %autorelease
Summary:        Tempfile implementation with a global registry to assure cleanup

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/gix-tempfile
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A tempfile implementation with a global registry to assure cleanup.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+document-features-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+document-features-devel %{_description}

This package contains library source intended for building other packages which
use the "document-features" feature of the "%{crate}" crate.

%files       -n %{name}+document-features-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hp-hashmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hp-hashmap-devel %{_description}

This package contains library source intended for building other packages which
use the "hp-hashmap" feature of the "%{crate}" crate.

%files       -n %{name}+hp-hashmap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+signals-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+signals-devel %{_description}

This package contains library source intended for building other packages which
use the "signals" feature of the "%{crate}" crate.

%files       -n %{name}+signals-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
