# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate csscolorparser

Name:           rust-csscolorparser
Version:        0.8.1
Release:        %autorelease
Summary:        CSS color parser library

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/csscolorparser
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
CSS color parser library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cint-devel %{_description}

This package contains library source intended for building other packages which
use the "cint" feature of the "%{crate}" crate.

%files       -n %{name}+cint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+named-colors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+named-colors-devel %{_description}

This package contains library source intended for building other packages which
use the "named-colors" feature of the "%{crate}" crate.

%files       -n %{name}+named-colors-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rust-rgb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rust-rgb-devel %{_description}

This package contains library source intended for building other packages which
use the "rust-rgb" feature of the "%{crate}" crate.

%files       -n %{name}+rust-rgb-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
