# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate cyclonedx-bom

Name:           rust-cyclonedx-bom
Version:        0.8.1
Release:        %autorelease
Summary:        CycloneDX Software Bill of Materials Library

License:        Apache-2.0
URL:            https://crates.io/crates/cyclonedx-bom
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
CycloneDX Software Bill of Materials Library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# Snapshots with XML data have a trivial case difference:
# -<?xml version="1.0" encoding="utf-8"?>
# +<?xml version="1.0" encoding="UTF-8"?>
find src/specs/ -type f -name '*.snap' -print -exec \
    sed -r -i 's/^(<\?xml .*encoding=")utf-8"/\1UTF-8"/' '{}' '+'

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * Upstream snapshots have defectively escaped XML output (> in version ranges
#   not escaped to &gt;), while we see correctly-escaped XML.
%{cargo_test -- -- --exact %{shrink:
    --skip specs::common::bom::v1_4::test::it_should_serialize_a_complex_example_to_xml
    --skip specs::common::bom::v1_5::test::it_should_serialize_a_complex_example_to_xml
    --skip specs::common::vulnerability::v1_4::test::it_should_write_xml_full
    --skip specs::common::vulnerability::v1_5::test::it_should_write_xml_full
    --skip specs::common::vulnerability_target::test::it_should_write_xml_full
    --skip specs::common::vulnerability_target::test::write_xml_versions_defined
}}
%endif

%changelog
%autochangelog
