# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate humantime-serde

Name:           rust-humantime-serde
Version:        1.1.1
Release:        %autorelease
Summary:        Serde support for the humantime crate

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/humantime-serde
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * bump version-sync dev-dependency from 0.8 to 0.9
Patch:          humantime-serde-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Serde support for the `humantime` crate.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * ignore failing tests that are only useful as upstream pre-release checklist
%cargo_test -- -- --skip test::test_html_root_url --skip test::test_readme_deps
%endif

%changelog
%autochangelog
