# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate build_html

Name:           rust-build_html
Version:        2.5.0
Release:        %autorelease
Summary:        Library for basic server-side rendering written in pure rust

License:        MIT
URL:            https://crates.io/crates/build_html
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  sed

%global _description %{expand:
Library for basic server-side rendering written in pure rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
sed -i 's/\r$//' README.md
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
