# Generated by rust2rpm 27
%bcond check 1

%global crate szip

Name:           rust-szip
Version:        1.0.0
Release:        %autorelease
Summary:        Fast command line tool for snappy compression and decompression

License:        BSD-3-Clause
URL:            https://crates.io/crates/szip
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  help2man

%global _description %{expand:
A fast command line tool for snappy compression and decompression.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# BSD-3-Clause
# MIT
# MIT OR Apache-2.0
License:        BSD-3-Clause AND MIT AND (MIT OR Apache-2.0)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license COPYING
%license LICENSE.dependencies
%doc README.md
%{_bindir}/szip
%{_mandir}/man1/szip.1*

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
help2man --no-info --output=szip.1 target/rpm/szip

%install
%cargo_install
install -t %{buildroot}%{_mandir}/man1 -D -p -m 0644 szip.1

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
