# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate log

Name:           rust-log0.3
Version:        0.3.9
Release:        %autorelease
Summary:        Lightweight logging facade for Rust

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/log
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A lightweight logging facade for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+max_level_debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_debug-devel %{_description}

This package contains library source intended for building other packages which
use the "max_level_debug" feature of the "%{crate}" crate.

%files       -n %{name}+max_level_debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+max_level_error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_error-devel %{_description}

This package contains library source intended for building other packages which
use the "max_level_error" feature of the "%{crate}" crate.

%files       -n %{name}+max_level_error-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+max_level_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_info-devel %{_description}

This package contains library source intended for building other packages which
use the "max_level_info" feature of the "%{crate}" crate.

%files       -n %{name}+max_level_info-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+max_level_off-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_off-devel %{_description}

This package contains library source intended for building other packages which
use the "max_level_off" feature of the "%{crate}" crate.

%files       -n %{name}+max_level_off-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+max_level_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_trace-devel %{_description}

This package contains library source intended for building other packages which
use the "max_level_trace" feature of the "%{crate}" crate.

%files       -n %{name}+max_level_trace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+max_level_warn-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_warn-devel %{_description}

This package contains library source intended for building other packages which
use the "max_level_warn" feature of the "%{crate}" crate.

%files       -n %{name}+max_level_warn-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly" feature of the "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+release_max_level_debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_debug-devel %{_description}

This package contains library source intended for building other packages which
use the "release_max_level_debug" feature of the "%{crate}" crate.

%files       -n %{name}+release_max_level_debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+release_max_level_error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_error-devel %{_description}

This package contains library source intended for building other packages which
use the "release_max_level_error" feature of the "%{crate}" crate.

%files       -n %{name}+release_max_level_error-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+release_max_level_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_info-devel %{_description}

This package contains library source intended for building other packages which
use the "release_max_level_info" feature of the "%{crate}" crate.

%files       -n %{name}+release_max_level_info-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+release_max_level_off-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_off-devel %{_description}

This package contains library source intended for building other packages which
use the "release_max_level_off" feature of the "%{crate}" crate.

%files       -n %{name}+release_max_level_off-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+release_max_level_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_trace-devel %{_description}

This package contains library source intended for building other packages which
use the "release_max_level_trace" feature of the "%{crate}" crate.

%files       -n %{name}+release_max_level_trace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+release_max_level_warn-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_warn-devel %{_description}

This package contains library source intended for building other packages which
use the "release_max_level_warn" feature of the "%{crate}" crate.

%files       -n %{name}+release_max_level_warn-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_std-devel %{_description}

This package contains library source intended for building other packages which
use the "use_std" feature of the "%{crate}" crate.

%files       -n %{name}+use_std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
