# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate bitflags

Name:           rust-bitflags1
Version:        1.3.2
Release:        %autorelease
Summary:        Macro to generate structures which behave like bitflags

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/bitflags
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop dependencies on compiler internals
Patch:          bitflags-fix-metadata.diff
# * upstream patch to fix building tests with trybuild >= 1.0.57
Patch:          https://github.com/bitflags/bitflags/commit/44c7063.patch

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A macro to generate structures which behave like bitflags.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+example_generated-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+example_generated-devel %{_description}

This package contains library source intended for building other packages which
use the "example_generated" feature of the "%{crate}" crate.

%files       -n %{name}+example_generated-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip trybuild tests that are broken due to cosmetic string differences
%cargo_test -- -- --skip fail
%endif

%changelog
%autochangelog
