# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate tls_codec_derive

Name:           rust-tls_codec_derive
Version:        0.4.2
Release:        %autorelease
Summary:        Derive macros for the tls_codec trait

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/tls_codec_derive
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Derive macros for the tls_codec trait.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+conditional_deserialization-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+conditional_deserialization-devel %{_description}

This package contains library source intended for building other packages which
use the "conditional_deserialization" feature of the "%{crate}" crate.

%files       -n %{name}+conditional_deserialization-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
