# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate gvdb

Name:           rust-gvdb
Version:        0.9.0
Release:        %autorelease
Summary:        Implementation of the glib gvdb file format

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/gvdb
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Implementation of the glib gvdb file format.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSES/Apache-2.0.txt
%license %{crate_instdir}/LICENSES/MIT.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/
%exclude %{crate_instdir}/test-data/
%exclude %{crate_instdir}/LICENSES/CC0-1.0.txt

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glib-devel %{_description}

This package contains library source intended for building other packages which
use the "glib" feature of the "%{crate}" crate.

%files       -n %{name}+glib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gresource-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gresource-devel %{_description}

This package contains library source intended for building other packages which
use the "gresource" feature of the "%{crate}" crate.

%files       -n %{name}+gresource-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mmap-devel %{_description}

This package contains library source intended for building other packages which
use the "mmap" feature of the "%{crate}" crate.

%files       -n %{name}+mmap-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
%autochangelog
