# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate winit

Name:           rust-winit
Version:        0.30.7
Release:        %autorelease
Summary:        Cross-platform window creation library

License:        Apache-2.0
URL:            https://crates.io/crates/winit
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          winit-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
# * Remove examples and example-only dependencies
# * Remove unwanted dependency raw-window-handle 0.4
Patch:          winit-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cross-platform window creation library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/FEATURES.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ahash-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ahash-devel %{_description}

This package contains library source intended for building other packages which
use the "ahash" feature of the "%{crate}" crate.

%files       -n %{name}+ahash-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytemuck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytemuck-devel %{_description}

This package contains library source intended for building other packages which
use the "bytemuck" feature of the "%{crate}" crate.

%files       -n %{name}+bytemuck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+memmap2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+memmap2-devel %{_description}

This package contains library source intended for building other packages which
use the "memmap2" feature of the "%{crate}" crate.

%files       -n %{name}+memmap2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mint-devel %{_description}

This package contains library source intended for building other packages which
use the "mint" feature of the "%{crate}" crate.

%files       -n %{name}+mint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+percent-encoding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+percent-encoding-devel %{_description}

This package contains library source intended for building other packages which
use the "percent-encoding" feature of the "%{crate}" crate.

%files       -n %{name}+percent-encoding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rwh_05-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rwh_05-devel %{_description}

This package contains library source intended for building other packages which
use the "rwh_05" feature of the "%{crate}" crate.

%files       -n %{name}+rwh_05-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rwh_06-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rwh_06-devel %{_description}

This package contains library source intended for building other packages which
use the "rwh_06" feature of the "%{crate}" crate.

%files       -n %{name}+rwh_06-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sctk-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sctk-devel %{_description}

This package contains library source intended for building other packages which
use the "sctk" feature of the "%{crate}" crate.

%files       -n %{name}+sctk-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sctk-adwaita-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sctk-adwaita-devel %{_description}

This package contains library source intended for building other packages which
use the "sctk-adwaita" feature of the "%{crate}" crate.

%files       -n %{name}+sctk-adwaita-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-backend" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-client-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-client-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-client" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-client-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-csd-adwaita-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-csd-adwaita-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-csd-adwaita" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-csd-adwaita-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-csd-adwaita-crossfont-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-csd-adwaita-crossfont-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-csd-adwaita-crossfont" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-csd-adwaita-crossfont-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-csd-adwaita-notitle-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-csd-adwaita-notitle-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-csd-adwaita-notitle" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-csd-adwaita-notitle-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-dlopen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-dlopen-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-dlopen" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-dlopen-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-protocols-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-protocols-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-protocols" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-protocols-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-protocols-plasma-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-protocols-plasma-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-protocols-plasma" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-protocols-plasma-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+x11-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+x11-devel %{_description}

This package contains library source intended for building other packages which
use the "x11" feature of the "%{crate}" crate.

%files       -n %{name}+x11-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+x11-dl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+x11-dl-devel %{_description}

This package contains library source intended for building other packages which
use the "x11-dl" feature of the "%{crate}" crate.

%files       -n %{name}+x11-dl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+x11rb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+x11rb-devel %{_description}

This package contains library source intended for building other packages which
use the "x11rb" feature of the "%{crate}" crate.

%files       -n %{name}+x11rb-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# Remove examples (unpackaged dependencies)
rm -rf examples/

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
