# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

# prevent executables from being installed
%global cargo_install_bin 0

%global crate uu_base64

Name:           rust-uu_base64
Version:        0.7.0
Release:        %autorelease
Summary:        base64 ~ (uutils) decode/encode input (base64-encoding)

License:        MIT
URL:            https://crates.io/crates/uu_base64
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop benchmarking dependencies like divan
Patch:          uu_base64-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
base64 ~ (uutils) decode/encode input (base64-encoding).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.package.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
