# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate filesize

Name:           rust-filesize
Version:        0.2.0
Release:        %autorelease
Summary:        Find the physical space used by a file

License:        MIT
URL:            https://crates.io/crates/filesize
Source:         %{crates_source}
# Automatically generated patch to strip foreign dependencies
Patch:          filesize-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Find the physical space used by a file.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
