# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate constant_time_eq

Name:           rust-constant_time_eq
Version:        0.3.1
Release:        %autorelease
Summary:        Compares two equal-sized byte strings in constant time

License:        MIT-0 OR Apache-2.0
URL:            https://crates.io/crates/constant_time_eq
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * remove CC0-1.0 from license metadata (not acceptable for code in Fedora)
# * drop unused, benchmark-only criterion dev-dependency to speed up builds
# * drop unused count_instructions dev-dependency and associated feature
Patch:          constant_time_eq-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Compares two equal-sized byte strings in constant time.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-CC0
%license %{crate_instdir}/LICENSE-MIT0
%doc %{crate_instdir}/README
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
