# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate logos-codegen

Name:           rust-logos-codegen
Version:        0.13.0
Release:        %autorelease
Summary:        Implementation details for logos-codegen and logos-derive

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/logos-codegen
Source0:        %{crates_source}
Source1:        https://github.com/maciejhirsz/logos/raw/v0.13/LICENSE-APACHE
Source2:        https://github.com/maciejhirsz/logos/raw/v0.13/LICENSE-MIT


BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Implementation details for logos-codegen and logos-derive. Not for
public consumption.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%doc %{crate_instdir}/README.md
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/


%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
cp -pav %{SOURCE1} %{SOURCE2} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
