# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate bpaf

Name:           rust-bpaf
Version:        0.9.15
Release:        %autorelease
Summary:        Simple Command Line Argument Parser with parser combinators

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/bpaf
Source:         %{crates_source}
Patch:          0001-use-correct-import-statement-to-fix-compilation-of-t.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A simple Command Line Argument Parser with parser combinators.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+autocomplete-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+autocomplete-devel %{_description}

This package contains library source intended for building other packages which
use the "autocomplete" feature of the "%{crate}" crate.

%files       -n %{name}+autocomplete-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+batteries-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+batteries-devel %{_description}

This package contains library source intended for building other packages which
use the "batteries" feature of the "%{crate}" crate.

%files       -n %{name}+batteries-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bpaf_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bpaf_derive-devel %{_description}

This package contains library source intended for building other packages which
use the "bpaf_derive" feature of the "%{crate}" crate.

%files       -n %{name}+bpaf_derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bright-color-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bright-color-devel %{_description}

This package contains library source intended for building other packages which
use the "bright-color" feature of the "%{crate}" crate.

%files       -n %{name}+bright-color-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+color-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+color-devel %{_description}

This package contains library source intended for building other packages which
use the "color" feature of the "%{crate}" crate.

%files       -n %{name}+color-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive-devel %{_description}

This package contains library source intended for building other packages which
use the "derive" feature of the "%{crate}" crate.

%files       -n %{name}+derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+docgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+docgen-devel %{_description}

This package contains library source intended for building other packages which
use the "docgen" feature of the "%{crate}" crate.

%files       -n %{name}+docgen-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dull-color-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dull-color-devel %{_description}

This package contains library source intended for building other packages which
use the "dull-color" feature of the "%{crate}" crate.

%files       -n %{name}+dull-color-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+extradocs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+extradocs-devel %{_description}

This package contains library source intended for building other packages which
use the "extradocs" feature of the "%{crate}" crate.

%files       -n %{name}+extradocs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+owo-colors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+owo-colors-devel %{_description}

This package contains library source intended for building other packages which
use the "owo-colors" feature of the "%{crate}" crate.

%files       -n %{name}+owo-colors-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+supports-color-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+supports-color-devel %{_description}

This package contains library source intended for building other packages which
use the "supports-color" feature of the "%{crate}" crate.

%files       -n %{name}+supports-color-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-docs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-docs-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable-docs" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-docs-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f autocomplete,derive

%build
%cargo_build -f autocomplete,derive

%install
%cargo_install -f autocomplete,derive

%if %{with check}
%check
# * skip one test that fails for yet unknown reasons
%cargo_test -f autocomplete,derive -- -- --exact --skip buffer::splitter::ticks_code_block
%endif

%changelog
%autochangelog
