# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate tame-index

Name:           rust-tame-index
Version:        0.12.0
Release:        %autorelease
Summary:        Access to local and remote cargo registry indices

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/tame-index
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * Bump gix to version 0.66
# * remove unused benchmark-only tiny-bench dev-dependency
Patch:          tame-index-fix-metadata.diff
# See https://github.com/EmbarkStudios/tame-index/commit/033b9d1e4187b9b967068adef283a40c86727ce6
Patch:          gix-compatibility.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Provides access to local and remote cargo registry indices.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+git-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+git-devel %{_description}

This package contains library source intended for building other packages which
use the "git" feature of the "%{crate}" crate.

%files       -n %{name}+git-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-devel %{_description}

This package contains library source intended for building other packages which
use the "local" feature of the "%{crate}" crate.

%files       -n %{name}+local-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-builder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-builder-devel %{_description}

This package contains library source intended for building other packages which
use the "local-builder" feature of the "%{crate}" crate.

%files       -n %{name}+local-builder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-certs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-certs-devel %{_description}

This package contains library source intended for building other packages which
use the "native-certs" feature of the "%{crate}" crate.

%files       -n %{name}+native-certs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sparse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sparse-devel %{_description}

This package contains library source intended for building other packages which
use the "sparse" feature of the "%{crate}" crate.

%files       -n %{name}+sparse-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
# * skip tests that require a cargo cache directory
# * skip tests that require internet connectivity
%cargo_test -a -- -- --exact --skip serializes_current_cargo_cache --skip parses_current_cargo_cache --skip can_take_shared_lock --skip wait_lock_times_out --skip waits_lock --skip clones_new --skip fetch_invalidates_cache --skip non_main_local_branch --skip opens_existing --skip updates_cache --skip builds_local_registry --skip downloads_and_verifies --skip remote::end_to_end --skip remote::reuses_connection --skip remote::async_reuses_connection
%endif

%changelog
%autochangelog
