# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate tree-sitter-loader

Name:           rust-tree-sitter-loader
Version:        0.22.5
Release:        %autorelease
Summary:        Locates, builds, and loads tree-sitter grammars at runtime

License:        MIT
URL:            https://crates.io/crates/tree-sitter-loader
Source:         %{crates_source}
# Upstream license file - tree-sitter/tree-sitter#1520
Source:         https://github.com/tree-sitter/tree-sitter/raw/v%{version}/LICENSE#/LICENSE.upstream
# Manually created patch for downstream crate metadata changes
# * Disable feature 'wasm'
Patch:          tree-sitter-loader-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Locates, builds, and loads tree-sitter grammars at runtime.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
cp -pav %{SOURCE1} LICENSE

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
