# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate fb_procfs

Name:           rust-fb_procfs0.7
Version:        0.7.1
Release:        %autorelease
Summary:        For reading procfs

License:        Apache-2.0
URL:            https://crates.io/crates/fb_procfs
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * bump nix dependency from v0.25 to v0.30
Patch:          fb_procfs-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A crate for reading procfs.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
