# Generated by rust2rpm 27
# * disable tests since /dev/kvm is unusable in containerized builds
%bcond check 0
%global debug_package %{nil}

%global crate kvm-ioctls

# compile and run tests only on supported architectures
%global supported_arches aarch64 riscv64 x86_64

Name:           rust-kvm-ioctls
Version:        0.19.1
Release:        %autorelease
Summary:        Safe wrappers over KVM ioctls

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/kvm-ioctls
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Safe wrappers over KVM ioctls.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/
%exclude %{crate_instdir}/CODEOWNERS
%exclude %{crate_instdir}/coverage_config_*.json

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%ifarch %{supported_arches}
%cargo_build
%endif

%install
%cargo_install

%if %{with check}
%ifarch %{supported_arches}
%check
%cargo_test
%endif
%endif

%changelog
%autochangelog
