# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate tree-sitter-scheme

Name:           rust-tree-sitter-scheme
Version:        0.24.7
Release:        %autorelease
Summary:        Scheme grammar for tree-sitter

License:        MIT
URL:            https://crates.io/crates/tree-sitter-scheme
Source:         %{crates_source}
# * LICENSE file not shipped, see
#   https://github.com/6cdh/tree-sitter-scheme/commit/b5c701148501fa056302827442b5b4956f1edc03
Source1:        https://raw.githubusercontent.com/6cdh/tree-sitter-scheme/refs/tags/v%{version}/LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Scheme grammar for tree-sitter.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
cp -p %{SOURCE1} .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
cp -p LICENSE %{buildroot}%{crate_instdir}/

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
