# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate thin-vec

Name:           rust-thin-vec
Version:        0.2.14
Release:        %autorelease
Summary:        Vec that takes up less space on the stack

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/thin-vec
Source:         %{crates_source}
# * Use core::mem::align_of to determine proper type aligment,
#   https://github.com/Gankra/thin-vec/pull/57
# * Fixes: "cargo test --features=serde" fails on i686,
#   https://github.com/Gankra/thin-vec/issues/56
Patch10:        https://github.com/Gankra/thin-vec/pull/57.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A vec that takes up less space on the stack.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/RELEASES.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gecko-ffi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gecko-ffi-devel %{_description}

This package contains library source intended for building other packages which
use the "gecko-ffi" feature of the "%{crate}" crate.

%files       -n %{name}+gecko-ffi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * The skipped test relies on a panic from a debug_assert, which does not
#   happen in release mode.
%cargo_test -- -- --skip std_tests::test_set_len_invalid
%endif

%changelog
%autochangelog
