# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate sluice

Name:           rust-sluice
Version:        0.6.0
Release:        %autorelease
Summary:        Efficient ring buffer for byte buffers, FIFO queues, and SPSC channels

License:        MIT
URL:            https://crates.io/crates/sluice
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * Drop unnecessary benchmark-only dev-dependency on criterion
Patch:          sluice-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Efficient ring buffer for byte buffers, FIFO queues, and SPSC channels.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
