# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate papaya

Name:           rust-papaya
Version:        0.2.4
Release:        %autorelease
Summary:        Fast and ergonomic concurrent hash-table for read-heavy workloads

License:        MIT
URL:            https://crates.io/crates/papaya
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * Drop unused, benchmark-only dev-dependencies on base64, criterion, dashmap,
#   and hdrhistogram
Patch:          papaya-fix-metadata.diff
# * Skip raw::alloc::layout on 32-bit targets
Patch10:        https://github.com/ibraheemdev/papaya/pull/98.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A fast and ergonomic concurrent hash-table for read-heavy workloads.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/BENCHMARKS.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
