# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate nu-ansi-term

Name:           rust-nu-ansi-term
Version:        0.50.3
Release:        %autorelease
Summary:        Library for ANSI terminal colors and styles (bold, underline)

License:        MIT
URL:            https://crates.io/crates/nu-ansi-term
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          nu-ansi-term-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  dos2unix

%global _description %{expand:
Library for ANSI terminal colors and styles (bold, underline).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive_serde_style-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive_serde_style-devel %{_description}

This package contains library source intended for building other packages which
use the "derive_serde_style" feature of the "%{crate}" crate.

%files       -n %{name}+derive_serde_style-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gnu_legacy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gnu_legacy-devel %{_description}

This package contains library source intended for building other packages which
use the "gnu_legacy" feature of the "%{crate}" crate.

%files       -n %{name}+gnu_legacy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# clean up CRLF line endings:
# https://github.com/nushell/nu-ansi-term/issues/73
find . -type f -exec dos2unix --keepdate '{}' '+'

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
