# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate base64-simd

Name:           rust-base64-simd
Version:        0.8.0
Release:        %autorelease
Summary:        SIMD-accelerated base64 encoding and decoding

License:        MIT
URL:            https://crates.io/crates/base64-simd
Source:         %{crates_source}
# * LICENSE file not shipped, see https://github.com/Nugine/simd/pull/47
Source2:        https://raw.githubusercontent.com/Nugine/simd/refs/tags/v0.8.0/LICENSE
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          base64-simd-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
# * bump base64 to 0.22, https://github.com/Nugine/simd/pull/58
# * bump const-str to 0.6, https://github.com/Nugine/simd/pull/54
Patch:          base64-simd-fix-metadata.diff
# * update base64 from 0.20.0 to 0.21.0
# * https://github.com/Nugine/simd/pull/30
Patch2:         base64-simd-update-base64-to-0_21.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
SIMD-accelerated base64 encoding and decoding.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+detect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+detect-devel %{_description}

This package contains library source intended for building other packages which
use the "detect" feature of the "%{crate}" crate.

%files       -n %{name}+detect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
cp -p %{SOURCE2} .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
