# Generated by rust2rpm 26
# * missing dev-dependency: rcgen ^0.11.3
%bcond_with check
%global debug_package %{nil}

%global crate h3

Name:           rust-h3
Version:        0.0.6
Release:        %autorelease
Summary:        Async HTTP/3 implementation

License:        MIT
URL:            https://crates.io/crates/h3
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An async HTTP/3 implementation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+i-implement-a-third-party-backend-and-opt-into-breaking-changes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+i-implement-a-third-party-backend-and-opt-into-breaking-changes-devel %{_description}

This package contains library source intended for building other packages which
use the "i-implement-a-third-party-backend-and-opt-into-breaking-changes" feature of the "%{crate}" crate.

%files       -n %{name}+i-implement-a-third-party-backend-and-opt-into-breaking-changes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
