# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate arrow-csv

Name:           rust-arrow-csv
Version:        57.3.0
Release:        %autorelease
Summary:        Support for parsing CSV format to and from the Arrow format

License:        Apache-2.0
URL:            https://crates.io/crates/arrow-csv
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Support for parsing CSV format to and from the Arrow format.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%license %{crate_instdir}/NOTICE.txt
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * missing fixtures
# * skip some s390x tests for endianness issues
%{cargo_test -- --lib -- --exact %{shrink:
    --skip reader::tests::test_buffered
    --skip reader::tests::test_csv
    --skip reader::tests::test_csv_builder_with_bounds
    --skip reader::tests::test_csv_from_buf_reader
    --skip reader::tests::test_csv_reader_with_decimal
    --skip reader::tests::test_csv_reader_with_decimal_3264
    --skip reader::tests::test_csv_schema_metadata
    --skip reader::tests::test_csv_with_dictionary
    --skip reader::tests::test_csv_with_nullable_dictionary
    --skip reader::tests::test_csv_with_projection
    --skip reader::tests::test_csv_with_schema_inference
    --skip reader::tests::test_csv_with_schema_inference_no_headers
    --skip reader::tests::test_custom_nulls
    --skip reader::tests::test_custom_nulls_with_inference
    --skip reader::tests::test_init_nulls
    --skip reader::tests::test_init_nulls_with_inference
    --skip reader::tests::test_nulls
    --skip reader::tests::test_nulls_with_inference
    --skip reader::tests::test_parse_invalid_csv_bool
    --skip reader::tests::test_parse_invalid_csv_float
    --skip reader::tests::test_parse_invalid_csv_int
    --skip reader::tests::test_scientific_notation_with_inference
    --skip reader::tests::test_truncated_rows_csv
%ifarch s390x
    --skip reader::tests::test_parse_string_view_multi_column
    --skip reader::tests::test_parse_string_view_single_column
    --skip writer::tests::test_write_csv_whitespace_all_string_types
%endif
}}
%endif

%changelog
%autochangelog
