# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate calamine

Name:           rust-calamine
Version:        0.24.0
Release:        %autorelease
Summary:        Excel/OpenDocument Spreadsheets reader and deserializer in pure rust

License:        MIT
URL:            https://crates.io/crates/calamine
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An Excel/OpenDocument Spreadsheets reader and deserializer in pure rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT.md
%doc %{crate_instdir}/Changelog.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dates-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dates-devel %{_description}

This package contains library source intended for building other packages which
use the "dates" feature of the "%{crate}" crate.

%files       -n %{name}+dates-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+once_cell-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+once_cell-devel %{_description}

This package contains library source intended for building other packages which
use the "once_cell" feature of the "%{crate}" crate.

%files       -n %{name}+once_cell-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+picture-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+picture-devel %{_description}

This package contains library source intended for building other packages which
use the "picture" feature of the "%{crate}" crate.

%files       -n %{name}+picture-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * most doc tests depend on unshipped fixtures
%cargo_test -- --lib
%endif

%changelog
%autochangelog
