# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate vhost

Name:           rust-vhost
Version:        0.13.0
Release:        %autorelease
Summary:        Pure rust library for vdpa, vhost and vhost-user

License:        Apache-2.0 OR BSD-3-Clause
URL:            https://crates.io/crates/vhost
Source0:        %{crates_source}
Source1:        https://raw.githubusercontent.com/rust-vmm/vhost/main/LICENSE
Source2:        https://raw.githubusercontent.com/rust-vmm/vhost/main/LICENSE-BSD-3-Clause
# Bump uuid crate dependency version to 1.11.0
# Upstream PR: https://github.com/rust-vmm/vhost/pull/278
Patch:          vhost-bump-uuid-version.diff

# We depend on vm-memory which does not support 32 bit targets
ExcludeArch:    %{ix86}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A pure rust library for vdpa, vhost and vhost-user.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/LICENSE-BSD-3-Clause
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+postcopy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+postcopy-devel %{_description}

This package contains library source intended for building other packages which
use the "postcopy" feature of the "%{crate}" crate.

%files       -n %{name}+postcopy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-utils-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-utils-devel %{_description}

This package contains library source intended for building other packages which
use the "test-utils" feature of the "%{crate}" crate.

%files       -n %{name}+test-utils-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-kern-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-kern-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-kern" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-kern-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-net-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-net-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-net" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-net-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-user-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-user-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-user" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-user-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-user-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-user-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-user-backend" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-user-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-user-frontend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-user-frontend-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-user-frontend" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-user-frontend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-vdpa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-vdpa-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-vdpa" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-vdpa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-vsock-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-vsock-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-vsock" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-vsock-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xen-devel %{_description}

This package contains library source intended for building other packages which
use the "xen" feature of the "%{crate}" crate.

%files       -n %{name}+xen-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
cp %{SOURCE1} .
cp %{SOURCE2} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
