%global giturl  https://github.com/stp/stp

Name:		stp
Version:	2.3.4
Release:	%autorelease
Summary:	Constraint solver/decision procedure

# MIT: the project as a whole
# MIT-Modern-Variant: lib/extlib-abc
# LGPL-2.0-or-later: lib/extlib-constbv
# BSD-3-Clause: include/stp/Simplifier/constantBitP/MersenneTwister.h
License:	MIT AND MIT-Modern-Variant AND LGPL-2.0-or-later AND BSD-3-Clause
URL:		https://stp.github.io/
VCS:		git:%{giturl}.git
Source0:	%{giturl}/archive/%{version}/%{name}-%{version}.tar.gz
# The code assumes that certain minisat names are variables, but in the Fedora
# package, they are macros instead, leading to build failures
Patch0:		%{name}-minisat-macros.patch
# Do not declare cryptominisat and minisat as public libs
# See https://bugzilla.redhat.com/show_bug.cgi?id=1981466
Patch1:		%{name}-private-libs.patch
# Distutils has been deprecated.  Use sysconfig instead.
# https://github.com/stp/stp/pull/450
Patch2:		%{name}-distutils.patch

# See https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval
ExcludeArch:	%{ix86}

BuildRequires:	bison
BuildRequires:	boost-devel
BuildRequires:	cmake
BuildRequires:	cmake(cryptominisat5)
BuildRequires:	cryptominisat
BuildRequires:	flex
BuildRequires:	gcc-c++
BuildRequires:	help2man
BuildRequires:	make
BuildRequires:	minisat2-devel
BuildRequires:	perl(Getopt::Long)
BuildRequires:	pkgconfig(gmp)
BuildRequires:	pkgconfig(sqlite3)
BuildRequires:	python3-devel

%description
STP (Simple Theorem Prover) is a constraint solver (also referred to as
a decision procedure or automated prover) aimed at solving constraints
generated by program analysis tools, theorem provers, automated bug
finders, intelligent fuzzers and model checkers.  STP has been used in
many research projects at Stanford, Berkeley, MIT, CMU and other
universities, as well as companies and government agencies.

The input to STP are formulas over the theory of bit-vectors and arrays
(this theory captures most expressions from languages like C/C++/Java
and Verilog), and the output of STP is a single bit of information that
indicates whether the formula is satisfiable or not.  If the input is
satisfiable, then it also generates a variable assignment to satisfy the
input formula.

Additional information can be found at https://stp.readthedocs.io/.

%package devel
License:	MIT
Summary:	Development files for STP constraint solver/decision procedure
Requires:	%{name}%{?_isa} = %{version}-%{release}

%description devel
Development files for the STP (Simple Theorem Prover),
a constraint solver (also referred to as a decision procedure
or automated prover).  Provides a static library.

%package -n python3-%{name}
License:	MIT
Summary:	Python 3 interface to STP
Requires:	%{name} = %{version}-%{release}
BuildArch:	noarch

%description -n python3-%{name}
Python 3 interface to STP.

%prep
%autosetup -p1

# We do not want to know about the order of member initializers
sed -i "s/-Wno-deprecated/-Wno-reorder/" CMakeLists.txt

# Fix the version number
sed -i 's/2\.3\.3/%{version}/' CMakeLists.txt

# Prevent useless rpaths
sed -e '/CMAKE_SKIP_BUILD_RPATH/s/FALSE/TRUE/' \
    -e '/SET(CMAKE_INSTALL_RPATH .*)/d' \
    -e '/CMAKE_INSTALL_RPATH_USE_LINK_PATH/s/TRUE/FALSE/' \
    -e '/isSystemDir/d' \
    -i CMakeLists.txt

%build
export CFLAGS='%{build_cflags} -I %{_includedir}/minisat'
export CXXFLAGS='%{build_cxxflags} -I %{_includedir}/minisat'
%cmake -DPYTHON_EXECUTABLE:FILEPATH=%{_bindir}/python%{python3_version} \
       -DPYTHON_LIBRARY:FILEPATH=%{_libdir}/libpython%{python3_version}.so \
       -DPYTHON_INCLUDE_DIR:FILEPATH=%{_includedir}/python%{python3_version}

# Fix the help2man invocation
sed -i "s,help2man,LD_LIBRARY_PATH=$PWD/%{_vpath_builddir}/lib &," \
    %{_vpath_builddir}/CMakeFiles/man_stp.dir/build.make

%cmake_build

%install
%cmake_install

# Fix the location of the man page
mkdir -p %{buildroot}%{_datadir}
mv %{buildroot}%{_prefix}/man %{buildroot}%{_datadir}/man

%files
%{_bindir}/stp
%{_bindir}/stp_simple
%{_libdir}/libstp.so.2*
%{_mandir}/man1/stp.1*
%doc AUTHORS README.markdown papers
%license LICENSE LICENSE_COMPONENTS

%files devel
%{_includedir}/stp/
%{_libdir}/cmake/STP/
%{_libdir}/libstp.so

%files -n python3-%{name}
%{python3_sitelib}/%{name}/

%changelog
%autochangelog
